version: '3.8'

services:
  app:
    build:
      target: development
    volumes:
      - ./app:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - DEBUG=true
    command: uvicorn app.main:app --host 0.0.0.0 --port 6773 --reload

  worker:
    build:
      target: development
    volumes:
      - ./app:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - DEBUG=true
    command: celery -A app.celery_app worker --loglevel=debug --concurrency=1

  nginx:
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
